name:                qq
version:             0.1.0.0
github:              "githubuser/qq"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2018 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/qq#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
  - parsec
  - cassava
  - vector
  - bytestring
  - attoparsec
  - io-streams
  - containers
  - mtl
  - hashmap
  - hashable 
  - transformers
  - lens
  - optparse-generic
  - optparse-applicative
  - async
executables:
  qq-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - qq
    - optparse-generic
    - optparse-applicative
    - io-streams
    - containers
    - vector
    - transformers
    - parsec
    - mtl
    - cassava
    - bytestring

tests:
  qq-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - qq
    - hspec
    - parsec
    - attoparsec
    - io-streams
    - bytestring
    - vector
    - containers
    - mtl
    - transformers
